import React, { useState, useEffect } from 'react';
import { 
  GitBranch, 
  GitPullRequest, 
  FolderGit2, 
  FileCode, 
  CheckCircle2, 
  AlertCircle, 
  ExternalLink, 
  Copy, 
  Plus, 
  RefreshCw, 
  Sparkles, 
  ShieldCheck, 
  FileText, 
  Key, 
  Eye, 
  EyeOff, 
  Check, 
  Cpu, 
  Globe, 
  Trash2,
  Send
} from 'lucide-react';
import { githubService } from '../../services/githubService';
import { geminiService } from '../../services/geminiService';
import { useAgents } from '../../context/AgentContext';
import confetti from 'canvas-confetti';

export default function RepoConnectorView() {
  const { websiteUrl, setSettingsOpen } = useAgents();

  // GitHub Credentials & State
  const [repoInput, setRepoInput] = useState('');
  const [githubToken, setGithubToken] = useState('');
  const [showToken, setShowToken] = useState(false);
  const [selectedBranch, setSelectedBranch] = useState('main');
  const [availableBranches, setAvailableBranches] = useState([]);

  // Connection & Scan Status
  const [isLoading, setIsLoading] = useState(false);
  const [errorMsg, setErrorMsg] = useState(null);
  const [successMsg, setSuccessMsg] = useState(null);

  // Active Connected Repository Data
  const [connectedRepo, setConnectedRepo] = useState(null);

  // Landing Page Content & Audit State
  const [landingPageContent, setLandingPageContent] = useState('');
  const [loadingLandingPage, setLoadingLandingPage] = useState(false);
  
  // AI Audit Results
  const [isAuditing, setIsAuditing] = useState(false);
  const [auditResult, setAuditResult] = useState(null);

  // Action Center Active Tab
  const [activeTab, setActiveTab] = useState('audit'); // 'audit' | 'schema' | 'geofiles' | 'blog'

  // Staged Files for PR
  const [stagedFiles, setStagedFiles] = useState([]);
  const [isDispatchingPr, setIsDispatchingPr] = useState(false);
  const [prResult, setPrResult] = useState(null);
  const [prTitle, setPrTitle] = useState('🚀 RankTop AI: Structured SEO, AEO & GEO Optimization Patch');
  const [prDescription, setPrDescription] = useState('Automated technical SEO improvements, structured JSON-LD schemas, llms.txt, and optimized metadata generated by RankTop AI Swarm.');

  // Generated State
  const [generatedSchema, setGeneratedSchema] = useState('');
  const [generatedRobots, setGeneratedRobots] = useState('');
  const [generatedLlms, setGeneratedLlms] = useState('');
  const [generatedSitemap, setGeneratedSitemap] = useState('');
  const [copiedKey, setCopiedKey] = useState(null);

  // Blog Generator State
  const [blogKeyword, setBlogKeyword] = useState('');
  const [blogFileName, setBlogFileName] = useState('');
  const [blogArticle, setBlogArticle] = useState('');
  const [isWritingBlog, setIsWritingBlog] = useState(false);

  // Load Saved Config on Mount
  useEffect(() => {
    const saved = githubService.getConfig();
    if (saved.repo) setRepoInput(saved.repo);
    if (saved.token) setGithubToken(saved.token);
    if (saved.branch) setSelectedBranch(saved.branch);
  }, []);

  const handleCopy = (key, text) => {
    navigator.clipboard.writeText(text);
    setCopiedKey(key);
    setTimeout(() => setCopiedKey(null), 2000);
  };

  // ── 1. Connect & Scan GitHub Repository ───────────────────────────────────
  const handleConnectGitHub = async (e) => {
    if (e) e.preventDefault();
    setErrorMsg(null);
    setSuccessMsg(null);
    setPrResult(null);

    let parsed;
    try {
      parsed = githubService.parseRepo(repoInput);
    } catch (err) {
      setErrorMsg(err.message);
      return;
    }

    setIsLoading(true);
    try {
      // 1. Get Repo Metadata
      const repoDetails = await githubService.getRepoDetails(parsed.owner, parsed.repo, githubToken);
      const defaultBranch = repoDetails.default_branch || selectedBranch || 'main';

      // 2. Fetch Branches
      const branches = await githubService.getBranches(parsed.owner, parsed.repo, githubToken);
      setAvailableBranches(branches.length ? branches : [defaultBranch]);

      const activeBranch = branches.includes(selectedBranch) ? selectedBranch : defaultBranch;
      setSelectedBranch(activeBranch);

      // 3. Fetch Full Repository Tree
      const treeData = await githubService.getRepoTree(parsed.owner, parsed.repo, activeBranch, githubToken);
      const filePaths = treeData.files.map((f) => f.path);

      // 4. Analyze Architecture & Find Landing Page
      const framework = githubService.detectFramework(filePaths);
      const landingPage = githubService.findLandingPage(filePaths);
      const blogDir = githubService.findBlogDirectory(filePaths);
      const coreFiles = githubService.checkCoreSeoFiles(filePaths);

      const repoData = {
        name: `${parsed.owner}/${parsed.repo}`,
        owner: parsed.owner,
        repo: parsed.repo,
        branch: activeBranch,
        files: treeData.files,
        framework,
        landingPage,
        blogDir,
        coreFiles,
        isPrivate: repoDetails.private,
        htmlUrl: repoDetails.html_url,
      };

      setConnectedRepo(repoData);
      setSuccessMsg(`Successfully connected to ${parsed.owner}/${parsed.repo} on branch "${activeBranch}"`);

      githubService.saveConfig({
        repo: `${parsed.owner}/${parsed.repo}`,
        token: githubToken,
        branch: activeBranch,
      });

      // Auto-fetch landing page code from repo
      await loadLandingPageCode(repoData);
    } catch (err) {
      console.error('[GitHub Connect Error]', err);
      setErrorMsg(err.message || 'Failed to connect to GitHub repository. Please verify the URL and Personal Access Token.');
    } finally {
      setIsLoading(false);
    }
  };

  // ── Helper: Load Landing Page Code ─────────────────────────────────────────
  const loadLandingPageCode = async (repoData) => {
    if (!repoData) return;
    setLoadingLandingPage(true);
    try {
      const fileData = await githubService.getFileContent(
        repoData.owner,
        repoData.repo,
        repoData.landingPage,
        repoData.branch,
        githubToken
      );
      if (fileData) {
        setLandingPageContent(fileData.content);
      } else {
        setLandingPageContent('// Landing page file not found in repository root');
      }
    } catch (err) {
      console.warn('[Landing Page Load]', err);
    } finally {
      setLoadingLandingPage(false);
    }
  };

  // ── 2. Run AI Technical SEO & AEO Code Audit ──────────────────────────────
  const handleRunAiAudit = async () => {
    if (!landingPageContent || landingPageContent.length < 10) {
      setErrorMsg('No landing page code loaded to audit.');
      return;
    }
    if (!geminiService.hasApiKey()) {
      setSettingsOpen(true);
      return;
    }

    setIsAuditing(true);
    setErrorMsg(null);

    const prompt = `You are a Senior SEO Engineer, Technical Architect, and AEO/GEO Optimization Specialist.
Analyze the following website landing page source code (${connectedRepo?.landingPage || 'landing page'}) for repository "${connectedRepo?.name || websiteUrl || 'website'}".

SOURCE CODE SNIPPET:
\`\`\`
${landingPageContent.slice(0, 12000)}
\`\`\`

Evaluate:
1. Title tag presence, length, and keyword targeting.
2. Meta description presence and compelling hook.
3. OpenGraph (og:title, og:description, og:image, og:url, og:type) & Twitter cards.
4. Canonical URL tag.
5. JSON-LD structured data (schema.org).
6. Heading hierarchy (H1, H2, H3).
7. AEO (Answer Engine) direct question-answer clarity & GEO readiness for ChatGPT/Perplexity/Claude.

Return ONLY a valid JSON object (no markdown, no code fences):
{
  "seoScore": <number 0-100>,
  "aeoScore": <number 0-100>,
  "geoScore": <number 0-100>,
  "titleStatus": { "found": <boolean>, "current": "<string>", "recommended": "<string>", "feedback": "<string>" },
  "descriptionStatus": { "found": <boolean>, "current": "<string>", "recommended": "<string>", "feedback": "<string>" },
  "openGraphStatus": { "hasOgTitle": <boolean>, "hasOgDesc": <boolean>, "hasOgImage": <boolean>, "feedback": "<string>" },
  "canonicalStatus": { "found": <boolean>, "feedback": "<string>" },
  "schemaStatus": { "found": <boolean>, "existingTypes": ["<type>"], "recommendedTypes": ["WebSite", "Organization", "FAQPage"] },
  "headingsStatus": { "h1Count": <number>, "feedback": "<string>" },
  "topIssues": ["<critical issue 1>", "<critical issue 2>", "<critical issue 3>"],
  "recommendedPatchCode": "<ready-to-paste clean HTML head snippet with full meta tags, OpenGraph, and JSON-LD schema>"
}`;

    try {
      const raw = await geminiService.generateContent(prompt);
      const cleaned = raw
        .replace(/^```json\s*/i, '')
        .replace(/^```\s*/i, '')
        .replace(/```\s*$/i, '')
        .trim();

      const parsed = JSON.parse(cleaned);
      setAuditResult(parsed);
      confetti({ particleCount: 40, spread: 60, origin: { y: 0.6 } });
    } catch (err) {
      console.error('[AI Audit Error]', err);
      setErrorMsg('Failed to parse AI Audit. Please verify your Gemini API key and try again.');
    } finally {
      setIsAuditing(false);
    }
  };

  // ── 3. Synthesize Deep JSON-LD Schema ──────────────────────────────────────
  const handleGenerateSchema = async () => {
    if (!geminiService.hasApiKey()) {
      setSettingsOpen(true);
      return;
    }
    const domain = connectedRepo?.name || websiteUrl || 'yourbrand.com';
    const prompt = `You are a Semantic Web & Schema.org Expert.
Generate a comprehensive, fully validated multi-entity JSON-LD schema graph for the website/project "${domain}".
Include:
1. @graph with WebSite entity including SearchAction target.
2. Organization / Brand entity with name, url, logo, sameAs social links.
3. FAQPage entity with 4 high-value customer questions and concise direct answers optimized for Google AI Overviews and Perplexity.

Return ONLY the raw <script type="application/ld+json">...</script> code block (no other explanation text).`;

    try {
      const raw = await geminiService.generateContent(prompt);
      const cleaned = raw.replace(/^```html\s*/i, '').replace(/^```\s*/i, '').replace(/```\s*$/i, '').trim();
      setGeneratedSchema(cleaned);
    } catch (err) {
      setErrorMsg('Failed to generate JSON-LD schema: ' + err.message);
    }
  };

  // ── 4. Generate GEO & Core Files (llms.txt, robots.txt, sitemap.xml) ───────
  const handleGenerateGeoFiles = () => {
    const domain = connectedRepo?.name || websiteUrl || 'https://yourdomain.com';
    const cleanUrl = domain.startsWith('http') ? domain : `https://${domain}`;

    // 1. llms.txt (Perplexity / Anthropic / OpenAI standard)
    const llms = `# ${connectedRepo?.name || 'RankTop AI'}\n\n> Autonomous SEO, AEO and Generative Engine Optimization Engine.\n\n## Overview\nThis project provides high-performance search intelligence, multi-agent AI orchestration, automated structured data generation, and autonomous content publishing for next-generation search engines.\n\n## Key Resources\n- Documentation: ${cleanUrl}/docs\n- Blog & Guides: ${cleanUrl}/blog\n- Pricing & Plans: ${cleanUrl}/pricing\n- Contact & Support: ${cleanUrl}/contact\n\n## Core Capabilities\n- Autonomous technical SEO auditing\n- JSON-LD structured schema synthesis\n- Google AI Overview & Perplexity citation engineering\n`;
    setGeneratedLlms(llms);

    // 2. robots.txt
    const robots = `# robots.txt generated by RankTop AI Engine\nUser-agent: *\nAllow: /\nDisallow: /api/\nDisallow: /admin/\n\n# AI Crawlers & Generative Engine Optimization\nUser-agent: GPTBot\nAllow: /\n\nUser-agent: ClaudeBot\nAllow: /\n\nUser-agent: PerplexityBot\nAllow: /\n\nUser-agent: Google-Extended\nAllow: /\n\n# Sitemap Location\nsitemap: ${cleanUrl}/sitemap.xml\n`;
    setGeneratedRobots(robots);

    // 3. sitemap.xml
    const sitemap = `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n  <url>\n    <loc>${cleanUrl}/</loc>\n    <lastmod>${new Date().toISOString().split('T')[0]}</lastmod>\n    <changefreq>daily</changefreq>\n    <priority>1.0</priority>\n  </url>\n  <url>\n    <loc>${cleanUrl}/blog</loc>\n    <lastmod>${new Date().toISOString().split('T')[0]}</lastmod>\n    <changefreq>weekly</changefreq>\n    <priority>0.8</priority>\n  </url>\n</urlset>`;
    setGeneratedSitemap(sitemap);
  };

  // ── 5. Generate Blog Post for Repository ───────────────────────────────────
  const handleGenerateBlogPost = async () => {
    if (!blogKeyword.trim()) {
      setErrorMsg('Please enter a target keyword for the blog post.');
      return;
    }
    if (!geminiService.hasApiKey()) {
      setSettingsOpen(true);
      return;
    }

    setIsWritingBlog(true);
    setErrorMsg(null);

    const slug = blogKeyword.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
    const filename = `${slug}.md`;
    setBlogFileName(filename);

    const prompt = `You are a World-Class Technical SEO Writer & Generative Engine Optimizer.
Write an authoritative, 2,000+ word markdown blog post targeting the high-intent keyword: "${blogKeyword}".
Website / Repo: "${connectedRepo?.name || websiteUrl || 'Your Website'}".

REQUIREMENTS:
1. Include full YAML frontmatter at the top:
---
title: "Engaging, High-CTR Title"
description: "Compelling 155-character meta description with primary keyword."
slug: "${slug}"
date: "${new Date().toISOString().split('T')[0]}"
author: "Editorial Team"
tags: ["SEO", "AEO", "Growth", "Guide"]
canonicalUrl: "${connectedRepo?.htmlUrl || 'https://yourwebsite.com'}/blog/${slug}"
---
2. Structured with Key Takeaways summary box (AEO/BLUF block).
3. In-depth H2 and H3 breakdown with actionable steps, code examples, tables, and statistics.
4. Comprehensive FAQ section with 5 high-frequency questions.
5. Ready for direct Git publishing into ${connectedRepo?.blogDir || 'content/posts'}/${filename}.

Return ONLY the complete raw markdown with frontmatter.`;

    try {
      const raw = await geminiService.generateContent(prompt);
      const cleaned = raw.replace(/^```markdown\s*/i, '').replace(/^```\s*/i, '').replace(/```\s*$/i, '').trim();
      setBlogArticle(cleaned);
      confetti({ particleCount: 30, spread: 50 });
    } catch (err) {
      setErrorMsg('Failed to generate article: ' + err.message);
    } finally {
      setIsWritingBlog(false);
    }
  };

  // ── 6. Staging & Dispatching Pull Requests ─────────────────────────────────
  const stageFile = (filePath, fileContent, title, message) => {
    setStagedFiles((prev) => {
      const filtered = prev.filter((f) => f.path !== filePath);
      return [
        ...filtered,
        {
          path: filePath,
          content: fileContent,
          title: title || filePath,
          message: message || `RankTop AI: Add/Update ${filePath}`,
        },
      ];
    });
    setSuccessMsg(`Staged "${filePath}" for GitHub Pull Request!`);
  };

  const removeStagedFile = (filePath) => {
    setStagedFiles((prev) => prev.filter((f) => f.path !== filePath));
  };

  const handleDispatchPullRequest = async () => {
    if (!stagedFiles.length) {
      setErrorMsg('No files staged to dispatch.');
      return;
    }
    if (!githubToken) {
      setErrorMsg('A GitHub Personal Access Token (PAT) with "repo" scope is required to create a Pull Request.');
      return;
    }

    setIsDispatchingPr(true);
    setErrorMsg(null);
    setPrResult(null);

    try {
      const result = await githubService.dispatchPullRequest({
        owner: connectedRepo.owner,
        repo: connectedRepo.repo,
        baseBranch: connectedRepo.branch || 'main',
        title: prTitle,
        body: prDescription + `\n\n### 📦 Staged Files Included:\n` + stagedFiles.map((f) => `- \`${f.path}\`: ${f.title}`).join('\n'),
        files: stagedFiles,
        token: githubToken,
      });

      setPrResult(result);
      setStagedFiles([]);
      confetti({ particleCount: 80, spread: 100, origin: { y: 0.5 } });
    } catch (err) {
      console.error('[Dispatch PR Error]', err);
      setErrorMsg(err.message || 'Failed to dispatch Pull Request to GitHub.');
    } finally {
      setIsDispatchingPr(false);
    }
  };

  return (
    <div className="w-full space-y-6 font-sans">
      
      {/* ─── Hero Header ─── */}
      <div className="bg-[#171717] p-6 sm:p-8 rounded-2xl border border-[#262626] relative overflow-hidden">
        <div className="absolute top-0 right-0 w-96 h-96 bg-[#3ECF8E]/5 rounded-full blur-3xl pointer-events-none" />
        
        <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4 relative z-10">
          <div className="space-y-2">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-[#3ECF8E]/10 text-[#3ECF8E] text-xs font-bold border border-[#3ECF8E]/20">
              <FolderGit2 className="w-3.5 h-3.5" />
              <span>AUTONOMOUS GITHUB REPOSITORY ENGINE</span>
            </div>
            <h1 className="text-2xl sm:text-3xl font-extrabold text-white tracking-tight">
              GitHub Repository Connector
            </h1>
            <p className="text-sm text-zinc-400 max-w-2xl leading-relaxed">
              Connect your website's GitHub repository. RankTop scans your landing page code, detects missing schemas and meta tags, generates AEO/GEO assets, and automatically opens clean Pull Requests to rank your site.
            </p>
          </div>

          {connectedRepo && (
            <div className="flex items-center gap-3 bg-[#121212] px-4 py-2.5 rounded-xl border border-[#3ECF8E]/30">
              <div className="w-2.5 h-2.5 rounded-full bg-[#3ECF8E] animate-pulse" />
              <div className="text-left">
                <span className="text-xs text-zinc-400 block">Connected Repo:</span>
                <span className="text-xs font-bold text-white font-mono">{connectedRepo.name}</span>
              </div>
            </div>
          )}
        </div>
      </div>

      {/* ─── Alerts & Banners ─── */}
      {errorMsg && (
        <div className="p-4 rounded-xl bg-red-500/10 border border-red-500/30 text-red-400 flex items-start gap-3 text-sm">
          <AlertCircle className="w-5 h-5 flex-shrink-0 mt-0.5" />
          <div className="flex-1 font-medium">{errorMsg}</div>
          <button onClick={() => setErrorMsg(null)} className="text-red-400 hover:text-white text-xs font-bold">Dismiss</button>
        </div>
      )}

      {successMsg && (
        <div className="p-4 rounded-xl bg-[#3ECF8E]/10 border border-[#3ECF8E]/30 text-[#3ECF8E] flex items-start gap-3 text-sm">
          <CheckCircle2 className="w-5 h-5 flex-shrink-0 mt-0.5" />
          <div className="flex-1 font-medium">{successMsg}</div>
          <button onClick={() => setSuccessMsg(null)} className="text-[#3ECF8E] hover:text-white text-xs font-bold">Dismiss</button>
        </div>
      )}

      {prResult && (
        <div className="p-6 rounded-2xl bg-gradient-to-r from-[#3ECF8E]/15 to-[#60a5fa]/10 border border-[#3ECF8E]/40 text-white space-y-3">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2 text-[#3ECF8E] font-bold text-base">
              <GitPullRequest className="w-5 h-5" />
              <span>Pull Request #{prResult.prNumber} Successfully Created!</span>
            </div>
            <span className="text-xs px-2.5 py-1 rounded bg-[#3ECF8E]/20 text-[#3ECF8E] font-mono font-bold">
              Branch: {prResult.branch}
            </span>
          </div>
          <p className="text-sm text-zinc-300">
            RankTop AI has created a new branch and dispatched your structured SEO patch directly to GitHub.
          </p>
          <div className="pt-2">
            <a
              href={prResult.prUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl bg-[#3ECF8E] hover:bg-[#34D399] text-black font-bold text-sm transition-all shadow-lg shadow-[#3ECF8E]/20"
            >
              <ExternalLink className="w-4 h-4" />
              <span>View Pull Request on GitHub</span>
            </a>
          </div>
        </div>
      )}

      {/* ─── GitHub Repository Connection Card ─── */}
      <div className="bg-[#171717] rounded-2xl border border-[#262626] p-6 space-y-6">
        
        <form onSubmit={handleConnectGitHub} className="space-y-4">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            
            {/* Repository Address */}
            <div className="space-y-1.5">
              <label className="text-xs font-bold text-zinc-300 flex items-center justify-between">
                <span>GitHub Repository URL or "owner/repo"</span>
                <span className="text-zinc-500 font-normal">e.g. https://github.com/owner/website</span>
              </label>
              <div className="relative">
                <input
                  type="text"
                  value={repoInput}
                  onChange={(e) => setRepoInput(e.target.value)}
                  placeholder="https://github.com/owner/your-website"
                  className="w-full px-4 py-3 bg-[#121212] border border-[#262626] focus:border-[#3ECF8E] rounded-xl text-sm text-white placeholder-zinc-600 focus:outline-none transition-colors"
                />
              </div>
            </div>

            {/* Personal Access Token */}
            <div className="space-y-1.5">
              <label className="text-xs font-bold text-zinc-300 flex items-center justify-between">
                <span className="flex items-center gap-1">
                  <Key className="w-3 h-3 text-[#3ECF8E]" />
                  GitHub Token (PAT)
                </span>
                <a
                  href="https://github.com/settings/tokens/new?scopes=repo&description=RankTop%20Autonomous%20SEO"
                  target="_blank"
                  rel="noreferrer"
                  className="text-xs text-[#60a5fa] hover:underline flex items-center gap-1"
                >
                  Generate Token <ExternalLink className="w-2.5 h-2.5" />
                </a>
              </label>
              <div className="relative">
                <input
                  type={showToken ? 'text' : 'password'}
                  value={githubToken}
                  onChange={(e) => setGithubToken(e.target.value)}
                  placeholder="ghp_xxxxxxxxxxxx (Required for Pull Requests & Private Repos)"
                  className="w-full pl-4 pr-10 py-3 bg-[#121212] border border-[#262626] focus:border-[#3ECF8E] rounded-xl text-sm text-white placeholder-zinc-600 focus:outline-none transition-colors font-mono"
                />
                <button
                  type="button"
                  onClick={() => setShowToken(!showToken)}
                  className="absolute right-3 top-3.5 text-zinc-500 hover:text-zinc-300"
                >
                  {showToken ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                </button>
              </div>
            </div>
          </div>

          {/* Quick Presets & Branch Selector */}
          <div className="flex flex-wrap items-center justify-between gap-3 pt-2">
            <div className="flex items-center gap-2">
              <span className="text-xs text-zinc-500 font-medium">Quick Presets:</span>
              <button
                type="button"
                onClick={() => setRepoInput('SNDP-Design/RankTop')}
                className="text-xs px-2.5 py-1 rounded-lg bg-[#121212] hover:bg-[#262626] text-zinc-300 border border-[#262626] transition-colors"
              >
                SNDP-Design/RankTop
              </button>
            </div>

            <div className="flex items-center gap-3">
              {availableBranches.length > 1 && (
                <div className="flex items-center gap-1.5 text-xs text-zinc-400">
                  <GitBranch className="w-3.5 h-3.5 text-zinc-500" />
                  <span>Branch:</span>
                  <select
                    value={selectedBranch}
                    onChange={(e) => setSelectedBranch(e.target.value)}
                    className="bg-[#121212] border border-[#262626] text-white text-xs rounded-lg px-2 py-1 focus:outline-none"
                  >
                    {availableBranches.map((b) => (
                      <option key={b} value={b}>{b}</option>
                    ))}
                  </select>
                </div>
              )}

              <button
                type="submit"
                disabled={isLoading || !repoInput.trim()}
                className="px-6 py-3 rounded-xl font-bold text-sm bg-[#3ECF8E] hover:bg-[#34D399] text-black flex items-center gap-2 transition-all shadow-md shadow-[#3ECF8E]/20 disabled:opacity-50 cursor-pointer"
              >
                {isLoading ? (
                  <>
                    <RefreshCw className="w-4 h-4 animate-spin" />
                    <span>Scanning Repository...</span>
                  </>
                ) : (
                  <>
                    <FolderGit2 className="w-4 h-4" />
                    <span>Connect & Scan Repository</span>
                  </>
                )}
              </button>
            </div>
          </div>
        </form>

      </div>

      {/* ─── Connected Repository Health & Architecture ─── */}
      {connectedRepo && (
        <div className="bg-[#171717] rounded-2xl border border-[#262626] p-6 space-y-6">
          <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 pb-4 border-b border-[#262626]">
            <div>
              <div className="flex items-center gap-2">
                <span className="text-lg font-bold text-white">{connectedRepo.name}</span>
                <span
                  className="px-2.5 py-0.5 rounded text-xs font-extrabold text-white"
                  style={{ backgroundColor: connectedRepo.framework?.badgeColor || '#3ECF8E' }}
                >
                  {connectedRepo.framework?.name}
                </span>
                {connectedRepo.isPrivate && (
                  <span className="px-2 py-0.5 rounded text-[11px] font-bold bg-amber-500/10 text-amber-400 border border-amber-500/20">
                    Private Repo
                  </span>
                )}
              </div>
              <p className="text-xs text-zinc-400 mt-1">
                Total Files Scanned: <span className="text-white font-mono font-bold">{connectedRepo.files?.length || 0}</span> • Blog Directory: <code className="text-[#3ECF8E] font-mono">{connectedRepo.blogDir}</code>
              </p>
            </div>

            <div className="flex items-center gap-2">
              <span className="text-xs text-zinc-400">Detected Landing Page:</span>
              <span className="px-3 py-1 rounded-lg bg-[#121212] border border-[#262626] text-xs font-mono font-bold text-[#3ECF8E]">
                {connectedRepo.landingPage}
              </span>
            </div>
          </div>

          {/* Core Search Engine Telemetry Grid */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
            <div className="p-4 bg-[#121212] rounded-xl border border-[#262626] space-y-1">
              <div className="flex items-center justify-between">
                <span className="text-xs font-bold text-zinc-400">robots.txt</span>
                {connectedRepo.coreFiles?.hasRobotsTxt ? (
                  <CheckCircle2 className="w-4 h-4 text-[#3ECF8E]" />
                ) : (
                  <AlertCircle className="w-4 h-4 text-amber-400" />
                )}
              </div>
              <span className={`text-xs font-semibold block ${connectedRepo.coreFiles?.hasRobotsTxt ? 'text-[#3ECF8E]' : 'text-amber-400'}`}>
                {connectedRepo.coreFiles?.hasRobotsTxt ? 'Configured ✓' : 'Missing File'}
              </span>
            </div>

            <div className="p-4 bg-[#121212] rounded-xl border border-[#262626] space-y-1">
              <div className="flex items-center justify-between">
                <span className="text-xs font-bold text-zinc-400">sitemap.xml</span>
                {connectedRepo.coreFiles?.hasSitemap ? (
                  <CheckCircle2 className="w-4 h-4 text-[#3ECF8E]" />
                ) : (
                  <AlertCircle className="w-4 h-4 text-amber-400" />
                )}
              </div>
              <span className={`text-xs font-semibold block ${connectedRepo.coreFiles?.hasSitemap ? 'text-[#3ECF8E]' : 'text-amber-400'}`}>
                {connectedRepo.coreFiles?.hasSitemap ? 'Indexed ✓' : 'Missing Sitemap'}
              </span>
            </div>

            <div className="p-4 bg-[#121212] rounded-xl border border-[#262626] space-y-1">
              <div className="flex items-center justify-between">
                <span className="text-xs font-bold text-zinc-400">llms.txt (GEO)</span>
                {connectedRepo.coreFiles?.hasLlmsTxt ? (
                  <CheckCircle2 className="w-4 h-4 text-[#a78bfa]" />
                ) : (
                  <AlertCircle className="w-4 h-4 text-zinc-500" />
                )}
              </div>
              <span className={`text-xs font-semibold block ${connectedRepo.coreFiles?.hasLlmsTxt ? 'text-[#a78bfa]' : 'text-zinc-500'}`}>
                {connectedRepo.coreFiles?.hasLlmsTxt ? 'AI Optimized ✓' : 'Recommended'}
              </span>
            </div>

            <div className="p-4 bg-[#121212] rounded-xl border border-[#262626] space-y-1">
              <div className="flex items-center justify-between">
                <span className="text-xs font-bold text-zinc-400">Framework</span>
                <Globe className="w-4 h-4 text-[#60a5fa]" />
              </div>
              <span className="text-xs font-semibold text-white truncate block">
                {connectedRepo.framework?.type}
              </span>
            </div>
          </div>
        </div>
      )}

      {/* ─── Staged Changes & PR Dispatcher Bar ─── */}
      {stagedFiles.length > 0 && (
        <div className="bg-[#1c1c1c] rounded-2xl border-2 border-[#3ECF8E]/50 p-6 space-y-4 shadow-xl shadow-[#3ECF8E]/5">
          <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
            <div className="space-y-1">
              <div className="flex items-center gap-2 text-[#3ECF8E] font-bold text-base">
                <GitPullRequest className="w-5 h-5" />
                <span>{stagedFiles.length} File{stagedFiles.length > 1 ? 's' : ''} Staged for Pull Request</span>
              </div>
              <p className="text-xs text-zinc-400">Review staged optimizations before opening a Pull Request on GitHub.</p>
            </div>

            <button
              onClick={handleDispatchPullRequest}
              disabled={isDispatchingPr}
              className="px-6 py-3 rounded-xl font-extrabold text-sm bg-[#3ECF8E] hover:bg-[#34D399] text-black flex items-center gap-2 shadow-lg shadow-[#3ECF8E]/25 transition-all cursor-pointer disabled:opacity-50"
            >
              {isDispatchingPr ? (
                <>
                  <RefreshCw className="w-4 h-4 animate-spin" />
                  <span>Opening Pull Request on GitHub...</span>
                </>
              ) : (
                <>
                  <Send className="w-4 h-4" />
                  <span>Dispatch Pull Request to GitHub</span>
                </>
              )}
            </button>
          </div>

          {/* Pull Request Details */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3 pt-2">
            <div>
              <label className="text-xs font-bold text-zinc-400 block mb-1">Pull Request Title</label>
              <input
                type="text"
                value={prTitle}
                onChange={(e) => setPrTitle(e.target.value)}
                className="w-full px-3 py-2 bg-[#121212] border border-[#262626] rounded-lg text-xs text-white"
              />
            </div>
            <div>
              <label className="text-xs font-bold text-zinc-400 block mb-1">Pull Request Summary</label>
              <input
                type="text"
                value={prDescription}
                onChange={(e) => setPrDescription(e.target.value)}
                className="w-full px-3 py-2 bg-[#121212] border border-[#262626] rounded-lg text-xs text-white"
              />
            </div>
          </div>

          {/* Staged Items List */}
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-3 pt-2">
            {stagedFiles.map((file) => (
              <div key={file.path} className="p-3 bg-[#121212] rounded-xl border border-[#262626] flex items-center justify-between text-xs">
                <div className="truncate mr-2">
                  <span className="font-mono font-bold text-white block truncate">{file.path}</span>
                  <span className="text-zinc-500 text-[11px] block truncate">{file.title}</span>
                </div>
                <button
                  onClick={() => removeStagedFile(file.path)}
                  className="p-1.5 text-zinc-500 hover:text-red-400 transition-colors"
                  title="Remove from stage"
                >
                  <Trash2 className="w-3.5 h-3.5" />
                </button>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* ─── Action Center Tabs ─── */}
      {connectedRepo && (
        <div className="space-y-4">
          
          {/* Navigation Bar */}
          <div className="flex flex-wrap items-center gap-2 bg-[#171717] p-2 rounded-2xl border border-[#262626]">
            <button
              onClick={() => setActiveTab('audit')}
              className={`px-4 py-2.5 rounded-xl text-xs font-bold flex items-center gap-2 transition-all ${
                activeTab === 'audit'
                  ? 'bg-[#3ECF8E] text-black shadow'
                  : 'text-zinc-400 hover:text-white bg-[#121212]'
              }`}
            >
              <Cpu className="w-4 h-4" />
              <span>Landing Page AI Audit & Fixes</span>
            </button>

            <button
              onClick={() => setActiveTab('schema')}
              className={`px-4 py-2.5 rounded-xl text-xs font-bold flex items-center gap-2 transition-all ${
                activeTab === 'schema'
                  ? 'bg-[#3ECF8E] text-black shadow'
                  : 'text-zinc-400 hover:text-white bg-[#121212]'
              }`}
            >
              <Sparkles className="w-4 h-4" />
              <span>JSON-LD Schema Synthesizer</span>
            </button>

            <button
              onClick={() => { setActiveTab('geofiles'); handleGenerateGeoFiles(); }}
              className={`px-4 py-2.5 rounded-xl text-xs font-bold flex items-center gap-2 transition-all ${
                activeTab === 'geofiles'
                  ? 'bg-[#3ECF8E] text-black shadow'
                  : 'text-zinc-400 hover:text-white bg-[#121212]'
              }`}
            >
              <FileCode className="w-4 h-4" />
              <span>llms.txt, robots.txt & Sitemaps</span>
            </button>

            <button
              onClick={() => setActiveTab('blog')}
              className={`px-4 py-2.5 rounded-xl text-xs font-bold flex items-center gap-2 transition-all ${
                activeTab === 'blog'
                  ? 'bg-[#3ECF8E] text-black shadow'
                  : 'text-zinc-400 hover:text-white bg-[#121212]'
              }`}
            >
              <FileText className="w-4 h-4" />
              <span>AI Blog Git-Publisher</span>
            </button>
          </div>

          {/* ─── TAB 1: Landing Page AI Audit ─── */}
          {activeTab === 'audit' && (
            <div className="bg-[#171717] rounded-2xl border border-[#262626] p-6 space-y-6">
              
              <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
                <div>
                  <h3 className="text-lg font-bold text-white">Landing Page Code Inspector</h3>
                  <p className="text-xs text-zinc-400 mt-0.5">
                    Inspecting <code className="text-[#3ECF8E] font-mono">{connectedRepo.landingPage}</code> directly from GitHub repository.
                  </p>
                </div>

                <button
                  onClick={handleRunAiAudit}
                  disabled={isAuditing || loadingLandingPage}
                  className="px-5 py-2.5 rounded-xl font-bold text-xs bg-[#3ECF8E] hover:bg-[#34D399] text-black flex items-center gap-2 transition-all shadow-md shadow-[#3ECF8E]/20 disabled:opacity-50 cursor-pointer"
                >
                  {isAuditing ? (
                    <>
                      <RefreshCw className="w-3.5 h-3.5 animate-spin" />
                      <span>Auditing Codebase with Gemini AI...</span>
                    </>
                  ) : (
                    <>
                      <Sparkles className="w-3.5 h-3.5" />
                      <span>Run AI SEO & Schema Code Audit</span>
                    </>
                  )}
                </button>
              </div>

              {/* Source Code Viewer Container */}
              <div className="bg-[#121212] rounded-xl border border-[#262626] overflow-hidden">
                <div className="px-4 py-2 bg-[#1a1a1a] border-b border-[#262626] flex items-center justify-between text-xs text-zinc-400">
                  <span className="font-mono">{connectedRepo.landingPage}</span>
                  <span>{landingPageContent.length.toLocaleString()} characters</span>
                </div>
                <pre className="p-4 text-xs font-mono text-zinc-300 max-h-60 overflow-y-auto leading-relaxed">
                  {landingPageContent || '// Loading code snippet from GitHub...'}
                </pre>
              </div>

              {/* Audit Results */}
              {auditResult && (
                <div className="space-y-6 pt-4 border-t border-[#262626]">
                  
                  {/* Scorecards */}
                  <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                    <div className="p-4 bg-[#121212] rounded-xl border border-[#262626] text-center space-y-1">
                      <span className="text-xs text-zinc-400 font-bold uppercase">Technical SEO Score</span>
                      <div className="text-3xl font-black text-[#3ECF8E]">{auditResult.seoScore}/100</div>
                    </div>
                    <div className="p-4 bg-[#121212] rounded-xl border border-[#262626] text-center space-y-1">
                      <span className="text-xs text-zinc-400 font-bold uppercase">AEO Answer Score</span>
                      <div className="text-3xl font-black text-[#60a5fa]">{auditResult.aeoScore}/100</div>
                    </div>
                    <div className="p-4 bg-[#121212] rounded-xl border border-[#262626] text-center space-y-1">
                      <span className="text-xs text-zinc-400 font-bold uppercase">GEO Citation Score</span>
                      <div className="text-3xl font-black text-[#a78bfa]">{auditResult.geoScore}/100</div>
                    </div>
                  </div>

                  {/* Findings Breakdown */}
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
                    <div className="p-4 bg-[#121212] rounded-xl border border-[#262626] space-y-3">
                      <h4 className="font-bold text-white text-sm flex items-center gap-2">
                        <CheckCircle2 className="w-4 h-4 text-[#3ECF8E]" />
                        Title & Meta Tag Analysis
                      </h4>
                      <div className="space-y-1">
                        <span className="text-zinc-500 font-semibold">Current Title:</span>
                        <div className="text-zinc-300 font-mono p-2 bg-[#171717] rounded border border-[#262626]">
                          {auditResult.titleStatus?.current || 'Not found in head'}
                        </div>
                      </div>
                      <div className="space-y-1">
                        <span className="text-[#3ECF8E] font-semibold">Recommended Title:</span>
                        <div className="text-white font-mono p-2 bg-[#3ECF8E]/10 rounded border border-[#3ECF8E]/30">
                          {auditResult.titleStatus?.recommended || 'RankTop AI — Autonomous SEO, AEO & GEO Engine'}
                        </div>
                      </div>
                    </div>

                    <div className="p-4 bg-[#121212] rounded-xl border border-[#262626] space-y-3">
                      <h4 className="font-bold text-white text-sm flex items-center gap-2">
                        <ShieldCheck className="w-4 h-4 text-[#60a5fa]" />
                        Critical Technical Findings
                      </h4>
                      <ul className="space-y-2">
                        {auditResult.topIssues?.map((issue, idx) => (
                          <li key={idx} className="flex items-start gap-2 text-zinc-300">
                            <span className="text-amber-400 font-bold">•</span>
                            <span>{issue}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  </div>

                  {/* Recommended Patch Code Block */}
                  {auditResult.recommendedPatchCode && (
                    <div className="space-y-2">
                      <div className="flex items-center justify-between">
                        <span className="text-xs font-bold text-white">Recommended Optimized &lt;head&gt; Patch</span>
                        <div className="flex items-center gap-2">
                          <button
                            onClick={() => handleCopy('patch', auditResult.recommendedPatchCode)}
                            className="px-3 py-1 rounded-lg bg-[#121212] hover:bg-[#262626] text-zinc-300 text-xs font-medium border border-[#262626] flex items-center gap-1.5"
                          >
                            {copiedKey === 'patch' ? <Check className="w-3.5 h-3.5 text-[#3ECF8E]" /> : <Copy className="w-3.5 h-3.5" />}
                            <span>Copy Patch</span>
                          </button>

                          <button
                            onClick={() => stageFile(connectedRepo.landingPage, auditResult.recommendedPatchCode, 'Landing Page SEO & Schema Patch')}
                            className="px-3 py-1 rounded-lg bg-[#3ECF8E] hover:bg-[#34D399] text-black text-xs font-bold flex items-center gap-1.5"
                          >
                            <Plus className="w-3.5 h-3.5" />
                            <span>Stage Patch for Pull Request</span>
                          </button>
                        </div>
                      </div>
                      <pre className="p-4 bg-[#121212] rounded-xl border border-[#262626] text-xs font-mono text-[#3ECF8E] max-h-72 overflow-y-auto leading-relaxed">
                        {auditResult.recommendedPatchCode}
                      </pre>
                    </div>
                  )}

                </div>
              )}

            </div>
          )}

          {/* ─── TAB 2: Schema Synthesizer ─── */}
          {activeTab === 'schema' && (
            <div className="bg-[#171717] rounded-2xl border border-[#262626] p-6 space-y-6">
              <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
                <div>
                  <h3 className="text-lg font-bold text-white">Multi-Entity JSON-LD Schema Synthesizer</h3>
                  <p className="text-xs text-zinc-400 mt-0.5">
                    Generate deep WebSite, Organization, and FAQPage schemas engineered for Google AI Overviews & Perplexity.
                  </p>
                </div>

                <button
                  onClick={handleGenerateSchema}
                  className="px-5 py-2.5 rounded-xl font-bold text-xs bg-[#3ECF8E] hover:bg-[#34D399] text-black flex items-center gap-2 transition-all shadow-md shadow-[#3ECF8E]/20"
                >
                  <Sparkles className="w-3.5 h-3.5" />
                  <span>Synthesize JSON-LD Schema</span>
                </button>
              </div>

              {generatedSchema ? (
                <div className="space-y-3">
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-bold text-zinc-400">Synthesized Schema Markup:</span>
                    <div className="flex items-center gap-2">
                      <button
                        onClick={() => handleCopy('schema', generatedSchema)}
                        className="px-3 py-1 rounded-lg bg-[#121212] hover:bg-[#262626] text-zinc-300 text-xs font-medium border border-[#262626] flex items-center gap-1.5"
                      >
                        {copiedKey === 'schema' ? <Check className="w-3.5 h-3.5 text-[#3ECF8E]" /> : <Copy className="w-3.5 h-3.5" />}
                        <span>Copy Schema</span>
                      </button>

                      <button
                        onClick={() => stageFile('public/schema.json', generatedSchema, 'Multi-Entity JSON-LD Schema')}
                        className="px-3 py-1 rounded-lg bg-[#3ECF8E] hover:bg-[#34D399] text-black text-xs font-bold flex items-center gap-1.5"
                      >
                        <Plus className="w-3.5 h-3.5" />
                        <span>Stage Schema for PR</span>
                      </button>
                    </div>
                  </div>
                  <pre className="p-4 bg-[#121212] rounded-xl border border-[#262626] text-xs font-mono text-[#a78bfa] max-h-80 overflow-y-auto leading-relaxed">
                    {generatedSchema}
                  </pre>
                </div>
              ) : (
                <div className="p-8 text-center bg-[#121212] rounded-xl border border-dashed border-[#262626] text-zinc-500 text-xs">
                  Click "Synthesize JSON-LD Schema" to generate production-ready structured data for your website.
                </div>
              )}
            </div>
          )}

          {/* ─── TAB 3: GEO Core Files ─── */}
          {activeTab === 'geofiles' && (
            <div className="bg-[#171717] rounded-2xl border border-[#262626] p-6 space-y-6">
              <div>
                <h3 className="text-lg font-bold text-white">Generative Engine (GEO) & Search Files</h3>
                <p className="text-xs text-zinc-400 mt-0.5">
                  Generate standard <code className="text-[#3ECF8E]">llms.txt</code>, <code className="text-[#3ECF8E]">robots.txt</code>, and <code className="text-[#3ECF8E]">sitemap.xml</code> with full AI bot permissions.
                </p>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                
                {/* llms.txt */}
                <div className="space-y-2">
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-bold text-white font-mono">llms.txt (GEO)</span>
                    <div className="flex items-center gap-1">
                      <button
                        onClick={() => handleCopy('llms', generatedLlms)}
                        className="p-1 text-zinc-400 hover:text-white"
                        title="Copy"
                      >
                        <Copy className="w-3.5 h-3.5" />
                      </button>
                      <button
                        onClick={() => stageFile('public/llms.txt', generatedLlms, 'llms.txt AI Citation Guide')}
                        className="px-2 py-0.5 rounded bg-[#a78bfa]/20 hover:bg-[#a78bfa]/30 text-[#a78bfa] text-xs font-bold"
                      >
                        Stage
                      </button>
                    </div>
                  </div>
                  <pre className="p-3 bg-[#121212] rounded-xl border border-[#262626] text-xs font-mono text-[#a78bfa] max-h-52 overflow-y-auto leading-relaxed">
                    {generatedLlms}
                  </pre>
                </div>

                {/* robots.txt */}
                <div className="space-y-2">
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-bold text-white font-mono">robots.txt</span>
                    <div className="flex items-center gap-1">
                      <button
                        onClick={() => handleCopy('robots', generatedRobots)}
                        className="p-1 text-zinc-400 hover:text-white"
                        title="Copy"
                      >
                        <Copy className="w-3.5 h-3.5" />
                      </button>
                      <button
                        onClick={() => stageFile('public/robots.txt', generatedRobots, 'robots.txt Crawler Rules')}
                        className="px-2 py-0.5 rounded bg-[#3ECF8E]/20 hover:bg-[#3ECF8E]/30 text-[#3ECF8E] text-xs font-bold"
                      >
                        Stage
                      </button>
                    </div>
                  </div>
                  <pre className="p-3 bg-[#121212] rounded-xl border border-[#262626] text-xs font-mono text-[#3ECF8E] max-h-52 overflow-y-auto leading-relaxed">
                    {generatedRobots}
                  </pre>
                </div>

                {/* sitemap.xml */}
                <div className="space-y-2">
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-bold text-white font-mono">sitemap.xml</span>
                    <div className="flex items-center gap-1">
                      <button
                        onClick={() => handleCopy('sitemap', generatedSitemap)}
                        className="p-1 text-zinc-400 hover:text-white"
                        title="Copy"
                      >
                        <Copy className="w-3.5 h-3.5" />
                      </button>
                      <button
                        onClick={() => stageFile('public/sitemap.xml', generatedSitemap, 'sitemap.xml Search Index')}
                        className="px-2 py-0.5 rounded bg-[#60a5fa]/20 hover:bg-[#60a5fa]/30 text-[#60a5fa] text-xs font-bold"
                      >
                        Stage
                      </button>
                    </div>
                  </div>
                  <pre className="p-3 bg-[#121212] rounded-xl border border-[#262626] text-xs font-mono text-[#60a5fa] max-h-52 overflow-y-auto leading-relaxed">
                    {generatedSitemap}
                  </pre>
                </div>

              </div>
            </div>
          )}

          {/* ─── TAB 4: AI Blog Git-Publisher ─── */}
          {activeTab === 'blog' && (
            <div className="bg-[#171717] rounded-2xl border border-[#262626] p-6 space-y-6">
              <div>
                <h3 className="text-lg font-bold text-white">Autonomous Git Blog Publisher</h3>
                <p className="text-xs text-zinc-400 mt-0.5">
                  Generate comprehensive 2,000+ word markdown/MDX articles with YAML frontmatter formatted directly for <code className="text-[#3ECF8E] font-mono">{connectedRepo.blogDir}</code>.
                </p>
              </div>

              <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-3">
                <input
                  type="text"
                  value={blogKeyword}
                  onChange={(e) => setBlogKeyword(e.target.value)}
                  placeholder="Enter target topic / keyword (e.g. Best AI SEO Strategies for 2026)"
                  className="flex-1 px-4 py-3 bg-[#121212] border border-[#262626] focus:border-[#3ECF8E] rounded-xl text-sm text-white placeholder-zinc-600 focus:outline-none"
                />

                <button
                  onClick={handleGenerateBlogPost}
                  disabled={isWritingBlog || !blogKeyword.trim()}
                  className="px-6 py-3 rounded-xl font-bold text-xs bg-[#3ECF8E] hover:bg-[#34D399] text-black flex items-center justify-center gap-2 transition-all shadow-md shadow-[#3ECF8E]/20 disabled:opacity-50 cursor-pointer"
                >
                  {isWritingBlog ? (
                    <>
                      <RefreshCw className="w-4 h-4 animate-spin" />
                      <span>Generating Article with AI Swarm...</span>
                    </>
                  ) : (
                    <>
                      <Sparkles className="w-4 h-4" />
                      <span>Write Git-Ready Article</span>
                    </>
                  )}
                </button>
              </div>

              {blogArticle && (
                <div className="space-y-3">
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-mono font-bold text-white">
                      Target Path: <span className="text-[#3ECF8E]">{connectedRepo.blogDir}/{blogFileName}</span>
                    </span>

                    <div className="flex items-center gap-2">
                      <button
                        onClick={() => handleCopy('blog', blogArticle)}
                        className="px-3 py-1 rounded-lg bg-[#121212] hover:bg-[#262626] text-zinc-300 text-xs font-medium border border-[#262626] flex items-center gap-1.5"
                      >
                        {copiedKey === 'blog' ? <Check className="w-3.5 h-3.5 text-[#3ECF8E]" /> : <Copy className="w-3.5 h-3.5" />}
                        <span>Copy Markdown</span>
                      </button>

                      <button
                        onClick={() => stageFile(`${connectedRepo.blogDir}/${blogFileName}`, blogArticle, `New Article: ${blogKeyword}`)}
                        className="px-3 py-1 rounded-lg bg-[#3ECF8E] hover:bg-[#34D399] text-black text-xs font-bold flex items-center gap-1.5"
                      >
                        <Plus className="w-3.5 h-3.5" />
                        <span>Stage Article for Pull Request</span>
                      </button>
                    </div>
                  </div>

                  <pre className="p-4 bg-[#121212] rounded-xl border border-[#262626] text-xs font-mono text-zinc-300 max-h-96 overflow-y-auto leading-relaxed whitespace-pre-wrap">
                    {blogArticle}
                  </pre>
                </div>
              )}
            </div>
          )}

        </div>
      )}

    </div>
  );
}
